version: '3'
services:
  app:
    image: amurpo/flask-app-app:latest
    container_name: flask-app
    ports:
     - "4000:4000"
    networks:
      - osobusa2-net
  backend:
    image: amurpo/flask-app-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - osobusa2-net 

networks:
  osobusa2-net:
