version: '3'
services:
  app:
    image: amurpo/osobusa-kun:latest
    container_name: flask-app
    ports:
      - "4000:4000"
    networks:
      - monitoring-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - monitoring-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana  # Create a volume for Grafana data
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - "3000:3000"
    networks:
      - monitoring-net
    depends_on:
      - prometheus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://prometheus:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:  # Define a Docker volume for Grafana data
  grafana-data:

networks:
  monitoring-net:
