services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    env_file:
     - .env
    mem_limit: 512m  # Limit container memory to 512MB
    ulimits:
     nofile: # Fix memory leak issue on some systems when LimitCORE=infinity (containerd)
      soft: 1048576
      hard: 1048576
    volumes:
      - ./mysql/oso.sql:/docker-entrypoint-initdb.d/oso.sql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf

    networks:
     - osobusa-net

  backend:
    build: ./FastAPI
    container_name: backend
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - osobusa-net 
  
  frontend:
    build: ./react-frontend
    container_name: frontend
    ports:
      - "3000:3000"
    env_file: .env
    networks:
      - osobusa-net

networks:
  osobusa-net:
