services:
  frontend:
    build: ./flask-frontend/
    container_name: frontend
    image: amurpo/frontend:latest
    ports:
     - "4000:4000"
    networks:
      - osobusa-network
  backend:
    build: ./go-backend-mongodb
    container_name: backend
    image: amurpo/backend:latest
    ports:
      - "8000:8000"
    env_file:
      - ./go-backend-mongodb/.env
    networks:
      - osobusa-network

networks:
  osobusa-network: