# templates/configmap.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-flask-app-chart.fullname" . }}-configmap
  labels:
    {{- include "my-flask-app-chart.labels" . | nindent 4 }}

