global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask-app'
    static_configs:
      - targets:
          - flask-app:4000
  - job_name: prometheus
    static_configs:
      - targets:
         - prometheus:9090
  - job_name: 'grafana'
    static_configs:
      - targets:
          - grafana:3000