apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: LoadBalancer


---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: flask-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
