# .github/actions/setup-python/action.yml
name: 'Setup Python Environment'
inputs:
  folder:
    required: true
  config:
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ fromJson(inputs.config).version }}
    
    - shell: bash
      working-directory: ${{ inputs.folder }}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage pytest
        coverage run -m pytest
        coverage xml -o coverage.xml