name: Build and Push Docker Images

on:
  push:
    paths:
      - 'FastAPI/**'
      - 'flask-frontend/**'
      - 'go-backend-mongodb/**'
      - 'react-frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  
          password: ${{ secrets.DOCKER_TOKEN }}      

      - name: Build and push FastAPI
        if: github.event_name == 'push' && contains(github.event.head_commit.message, 'FastAPI')
        uses: docker/build-push-action@v2
        with:
          context: ./FastAPI
          file: ./FastAPI/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/fastapi:latest
          push: true

      - name: Build and push Flask Frontend
        if: github.event_name == 'push' && contains(github.event.head_commit.message, 'flask-frontend')
        uses: docker/build-push-action@v2
        with:
          context: ./flask-frontend
          file: ./flask-frontend/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/flask-frontend:latest
          push: true

      - name: Build and push Go Backend
        if: github.event_name == 'push' && contains(github.event.head_commit.message, 'go-backend-mongodb')
        uses: docker/build-push-action@v2
        with:
          context: ./go-backend-mongodb
          file: ./go-backend-mongodb/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/go-backend:latest
          push: true

      - name: Build and push React Frontend
        if: github.event_name == 'push' && contains(github.event.head_commit.message, 'react-frontend')
        uses: docker/build-push-action@v2
        with:
          context: ./react-frontend
          file: ./react-frontend/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/react-frontend:latest
          push: true
