name: Build and Push Docker Images

on:
  push:
    paths:
      - 'FastAPI/**'
      - 'flask-frontend/**'
      - 'go-backend-mongodb/**'
      - 'react-frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  
          password: ${{ secrets.DOCKER_TOKEN }}      

      - name: Build and push FastAPI
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }} 
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q 'FastAPI/'; then
            docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi:latest ./FastAPI
            docker push ${{ secrets.DOCKER_USERNAME }}/fastapi:latest
          fi

      - name: Build and push Flask Frontend
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }} 
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q 'flask-frontend/'; then
            docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-frontend:latest ./flask-frontend
            docker push ${{ secrets.DOCKER_USERNAME }}/flask-frontend:latest
          fi

      - name: Build and push Go Backend
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }} 
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q 'go-backend-mongodb/'; then
            docker build -t ${{ secrets.DOCKER_USERNAME }}/go-backend:latest ./go-backend-mongodb
            docker push ${{ secrets.DOCKER_USERNAME }}/go-backend:latest
          fi

      - name: Build and push React Frontend
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }} 
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q 'react-frontend/'; then
            docker build -t ${{ secrets.DOCKER_USERNAME }}/react-frontend:latest ./react-frontend
            docker push ${{ secrets.DOCKER_USERNAME }}/react-frontend:latest
          fi
