name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}  # Set to your desired AWS region
      # Add other AWS environment variables as needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Create venv
        run: python3 -m venv venv

      - name: Install dependencies
        run: venv/bin/pip install -r requirements.txt

      - name: Copy venv and templates
        run: |
          mkdir -p deployment-package
          cp -r venv deployment-package/
          cp -r templates deployment-package/
          zip -r deployment-package/lambda_function.zip deployment-package/*
        working-directory: ${{ github.workspace }}

      - name: Check AWS CLI version
        run: aws --version

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name ${{ secrets.LAMBDAFNAME }} \
            --zip-file fileb://deployment-package/lambda_function.zip

      - name: Clean up deployment directory
        run: rm -rf deployment-package
